# -*- coding: utf-8 -*-
"""simple_analyse_taux_change.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HaHFo68ajbwnQZPWLZ1Fx2lVtD6KnBMB
"""

# simple_analyse_taux_change.py

# 1. Installer les outils (fait manuellement avec pip install ...)
#    S'assurer que les bibliothèques nécessaires sont installées :
#    pip install yfinance pandas pytest

# Importer les bibliothèques
import yfinance as yf          # Pour télécharger les données financières
import pandas as pd            # Pour travailler avec les données tabulaires (DataFrames)
from datetime import datetime, timedelta # Pour calculer les dates
import os                      # Pour vérifier si un fichier existe

# Nom du fichier CSV où les données seront sauvegardées
CSV_FILENAME = 'taux_change_eur_usd_simple.csv'

print(f"--- Début de l'analyse du taux de change EUR/USD ---")

# 2. Récupérer les données du taux de change pour les 30 derniers jours
try:
    end_date = datetime.today()
    # Calcule la date de début 30 jours avant la date de fin
    start_date = end_date - timedelta(days=30)

    print(f"Récupération des données pour EUR/USD=X du {start_date.strftime('%Y-%m-%d')} au {end_date.strftime('%Y-%m-%d')}...")

    # Télécharge les données historiques
    # interval='1d' pour avoir des données journalières
    # Ajout d'un jour à end_date car yfinance exclut la date de fin
    data = yf.Ticker("EURUSD=X").history(start=start_date, end=end_date + timedelta(days=1), interval='1d')

    if data.empty:
        print("Aucune donnée récupérée. Vérifiez le ticker ou la connexion internet.")
        # On sort du script si pas de données
        exit()

    print(f"Données récupérées avec succès ({len(data)} jours).")

    # 3. Enregistrer les données dans un fichier CSV
    # index=True inclut la colonne des dates dans le fichier CSV
    data.to_csv(CSV_FILENAME, index=True)
    print(f"Données enregistrées dans {CSV_FILENAME}")

except Exception as e:
    print(f"Erreur lors de la récupération ou de l'enregistrement des données : {e}")
    exit() # Quitte si une erreur survient ici

# 4. Charger les données depuis le fichier CSV
print(f"\nChargement des données depuis {CSV_FILENAME}...")
if not os.path.exists(CSV_FILENAME):
    print(f"Erreur : Le fichier {CSV_FILENAME} n'a pas été trouvé.")
    exit() # Quitte si le fichier n'existe pas (ce ne devrait pas arriver après l'étape 3 réussie, mais bonne pratique)

try:
    # Charge les données depuis le CSV
    # index_col=0 dit que la première colonne est l'index (les dates)
    # parse_dates=True convertit l'index en vrais objets dates
    loaded_data = pd.read_csv(CSV_FILENAME, index_col=0, parse_dates=True)

    if loaded_data.empty:
         print(f"Erreur: Le fichier {CSV_FILENAME} est vide après chargement.")
         exit()

    print("Données chargées avec succès.")

except Exception as e:
    print(f"Erreur lors du chargement des données depuis le CSV : {e}")
    exit() # Quitte si une erreur survient ici

# 5. Analyser la série temporelle
print("\n--- Analyse des Données ---")

# Utiliser la colonne 'Close' pour l'analyse du taux
close_prices = loaded_data['Close']

# a. Moyenne et écart-type
mean_rate = close_prices.mean()
std_dev = close_prices.std() # Peut être NaN si moins de 2 jours de données

print(f"Moyenne du taux de clôture : {mean_rate:.4f}")
print(f"Écart-type du taux de clôture : {std_dev:.4f}" if not pd.isna(std_dev) else "Écart-type : Insuffisant de données")

# b. Dates des maximums/minimums
min_rate = close_prices.min()
date_min = close_prices.idxmin() # Obtient l'index (la date) de la valeur minimale
max_rate = close_prices.max()
date_max = close_prices.idxmax() # Obtient l'index (la date) de la valeur maximale

print(f"Taux Minimum : {min_rate:.4f} (le {date_min.strftime('%Y-%m-%d')})")
print(f"Taux Maximum : {max_rate:.4f} (le {date_max.strftime('%Y-%m-%d')})")

# c. Variation journalière
# Calcule la différence entre le prix de clôture d'aujourd'hui et celui d'hier
# .dropna() enlève la première valeur qui est NaN (pas de jour précédent)
daily_changes = close_prices.diff().dropna()

print("\nVariations Journalières (quelques exemples) :")
# Affiche les 5 premières et 5 dernières variations s'il y en a assez
if not daily_changes.empty:
    print(daily_changes.head().apply(lambda x: f"{x:+.4f}")) # .apply pour formater avec le signe
    if len(daily_changes) > 10:
        print("...")
        print(daily_changes.tail().apply(lambda x: f"{x:+.4f}"))
    elif len(daily_changes) > 5:
         print(daily_changes.tail(len(daily_changes) - 5).apply(lambda x: f"{x:+.4f}"))
else:
    print("Pas de données pour calculer les variations journalières (moins de 2 jours).")


# d. Jours de hausse ou de baisse
# Compte les jours où la variation est positive (hausse) ou négative (baisse)
rising_days_count = (daily_changes > 0).sum()
falling_days_count = (daily_changes < 0).sum()

print(f"\nNombre de jours de hausse : {rising_days_count}")
print(f"Nombre de jours de baisse : {falling_days_count}")
# Les jours où la variation est nulle ne sont comptés ni en hausse ni en baisse

print("\n--- Fin de l'analyse ---")

# 6. Production du rapport (l'affichage ci-dessus fait office de rapport simple)

